-- Selecionando as colunas pedidas--
SELECT
A.DEPARTAMENTO,
B.DIVISAO,
A.MEDIA
FROM
(SELECT
A.DEPARTAMENTO,
MAX(A.MEDIA) AS MEDIA

-- Criando a tabela que vamos retirar as informações --    
FROM 
(SELECT
B.DEPARTAMENTO,
B.DIVISAO,
ROUND(AVG(A."Salario Bruto"- B."Total Desconto"),2) AS MEDIA
FROM
(SELECT
C.NOME,
SUM(COALESCE(B.VALOR,0)) AS "Salario Bruto"
FROM EMP_VENC AS A
LEFT JOIN VENCIMENTO AS B
ON B.COD_VENC = A.COD_VENC
RIGHT JOIN EMPREGADO AS C
ON A.MATR = C.MATR
GROUP BY C.NOME) AS A
LEFT JOIN 
(SELECT
E.NOME AS DIVISAO, 
D.NOME AS DEPARTAMENTO, 
C.NOME,
SUM(COALESCE(B.VALOR,0)) AS "Total Desconto"
FROM EMP_DESC AS A
LEFT JOIN DESCONTO AS B
ON A.COD_DESC = B.COD_DESC
RIGHT JOIN EMPREGADO AS C
ON A.MATR = C.MATR
LEFT JOIN DEPARTAMENTO AS D
ON C.LOTACAO = D.COD_DEP
LEFT JOIN DIVISAO AS E
ON C.LOTACAO_DIV = E.COD_DIVISAO 
GROUP BY C.NOME,DEPARTAMENTO,DIVISAO) AS B
ON A.NOME = B.NOME
GROUP BY B.DIVISAO,B.DEPARTAMENTO
ORDER BY MEDIA DESC) AS A
GROUP BY A.DEPARTAMENTO
ORDER BY MEDIA DESC) AS A
INNER JOIN (SELECT
B.DEPARTAMENTO,
B.DIVISAO,
ROUND(AVG(A."Salario Bruto"- B."Total Desconto"),2) AS MEDIA
FROM
(SELECT
C.NOME,
SUM(COALESCE(B.VALOR,0)) AS "Salario Bruto"
FROM EMP_VENC AS A
LEFT JOIN VENCIMENTO AS B
ON B.COD_VENC = A.COD_VENC
RIGHT JOIN EMPREGADO AS C
ON A.MATR = C.MATR
GROUP BY C.NOME) AS A
LEFT JOIN 
(SELECT
E.NOME AS DIVISAO, 
D.NOME AS DEPARTAMENTO, 
C.NOME,
SUM(COALESCE(B.VALOR,0)) AS "Total Desconto"
FROM EMP_DESC AS A
LEFT JOIN DESCONTO AS B
ON A.COD_DESC = B.COD_DESC
RIGHT JOIN EMPREGADO AS C
ON A.MATR = C.MATR
LEFT JOIN DEPARTAMENTO AS D
ON C.LOTACAO = D.COD_DEP
LEFT JOIN DIVISAO AS E
ON C.LOTACAO_DIV = E.COD_DIVISAO 
GROUP BY C.NOME,DEPARTAMENTO,DIVISAO) AS B
ON A.NOME = B.NOME
GROUP BY B.DIVISAO,B.DEPARTAMENTO
ORDER BY MEDIA DESC) AS B
ON A.MEDIA = B.MEDIA












